backend:
  name: github
  repo: nova-cloud/nova-cloud.github.io
  branch: dev # Branch to update (optional; defaults to master)
  #api_root: https://api.github.com
  #site_domain: nova-cloud.github.io
  #base_url: https://github.com
  auth_endpoint: auth
  #cms_label_prefix: netlify-cms/

local_backend: false

# This line should *not* be indented
publish_mode: editorial_workflow

show_preview_links: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          options: ["", "azure", "microsoft-365", "noticias"],
          multiple: true,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          options: ["primeros-pasos", "intermedio", "avanzado"],
          multiple: false,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }

      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "/"
    create: true # Allow users to create new pages
    extension: html
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "landing-pages"
    label: "Landing Page"
    folder: "_landing-pages"
    create: true # Allow users to create new pages
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "landing-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Background Image",
          name: "background-image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
